//
// !!! WARNING !!!
//
// This file was auto-generated using the tool/codegen.py script. To make
// modifications, edit tool/error.xml and re-run that script.
//

// clang-format off

#include "error.g.h"
#include <assert.h>

struct wpd_error_category_definition_t
{
    const char *str;
};

static struct wpd_error_category_definition_t error_category_definitions[] = {
    { "WPD_ERROR_CATEGORY_GLOBAL" },
    { "WPD_ERROR_CATEGORY_XCB" },
    { "WPD_ERROR_CATEGORY_FTW" },
    { "WPD_ERROR_CATEGORY_IMAGE" },
    { "WPD_ERROR_CATEGORY_DATA" },
    { "WPD_ERROR_CATEGORY_PARSE" },
    { "WPD_ERROR_CATEGORY_CONFIG" },
    { "WPD_ERROR_CATEGORY_IPC" },
    { "WPD_ERROR_CATEGORY_RPC" },
};

const char *
wpd_error_category_str(wpd_error_category_t error_category)
{
    return error_category_definitions[error_category].str;
}

struct wpd_error_definition_t
{
    wpd_error_category_t category;
    const char *str;
};

static struct wpd_error_definition_t error_definitions[] = {
    { WPD_ERROR_CATEGORY_GLOBAL, "WPD_ERROR_GLOBAL_SUCCESS" },
    { WPD_ERROR_CATEGORY_GLOBAL, "WPD_ERROR_GLOBAL_FAILURE" },
    { WPD_ERROR_CATEGORY_GLOBAL, "WPD_ERROR_GLOBAL_NULL_PARAM" },
    { WPD_ERROR_CATEGORY_GLOBAL, "WPD_ERROR_GLOBAL_ALREADY_RUNNING" },
    { WPD_ERROR_CATEGORY_XCB, "WPD_ERROR_XCB_GET_GEOMETRY_FAILED" },
    { WPD_ERROR_CATEGORY_FTW, "WPD_ERROR_FTW_UNKNOWN_EXTENSION" },
    { WPD_ERROR_CATEGORY_IMAGE, "WPD_ERROR_IMAGE_STBI_LOAD_FAILURE" },
    { WPD_ERROR_CATEGORY_DATA, "WPD_ERROR_DATA_SQLITE_OPEN_FAILURE" },
    { WPD_ERROR_CATEGORY_DATA, "WPD_ERROR_DATA_TABLE_CREATION_FAILURE" },
    { WPD_ERROR_CATEGORY_PARSE, "WPD_ERROR_PARSE_BOOL_INVALID" },
    { WPD_ERROR_CATEGORY_PARSE, "WPD_ERROR_PARSE_U32_NOT_A_DECIMAL" },
    { WPD_ERROR_CATEGORY_PARSE, "WPD_ERROR_PARSE_U32_TRAILING_CHARS" },
    { WPD_ERROR_CATEGORY_PARSE, "WPD_ERROR_PARSE_U32_STRTOULL_OUT_OF_RANGE" },
    { WPD_ERROR_CATEGORY_PARSE, "WPD_ERROR_PARSE_U32_OVERFLOW" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_DUPLICATE_FIELD_DEFINITION" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_MISSING_YAML_MAP_ITEM_HANDLER" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_FILE_OPEN_FAILURE" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_FILE_DOES_NOT_EXIST" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_YAML_PARSER_LOAD_FAILURE" },
    { WPD_ERROR_CATEGORY_CONFIG, "WPD_ERROR_CONFIG_HOME_PATH_UNDEFINED" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_CREATE_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_GET_FLAGS" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_SET_FLAGS" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_CONNECT" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_INVALID_ADDRESS_PATH_LENGTH" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_REMOVE_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_BIND_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_LISTEN_ON_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_WRITE_TO_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_UNEXPECTED_WRITE_LENGTH" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_READ_FROM_SOCKET" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_UNEXPECTED_READ_LENGTH" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_ACCEPT_CONNECTION" },
    { WPD_ERROR_CATEGORY_IPC, "WPD_ERROR_IPC_FAILED_TO_CLOSE_SOCKET" },
    { WPD_ERROR_CATEGORY_RPC, "WPD_ERROR_RPC_UNEXPECTED_MESSAGE_TYPE" },
    { WPD_ERROR_CATEGORY_RPC, "WPD_ERROR_RPC_UNEXPECTED_RESPONSE_TYPE" },
    { WPD_ERROR_CATEGORY_RPC, "WPD_ERROR_RPC_REQUEST_TYPE_UNKNOWN" },
    { WPD_ERROR_CATEGORY_RPC, "WPD_ERROR_RPC_INVALID_MESSAGE" },
    { WPD_ERROR_CATEGORY_RPC, "WPD_ERROR_RPC_MISSING_REPONSE_ALLOCATOR" },
};

const char *
wpd_error_str(wpd_error_t error)
{
    return error_definitions[error].str;
}
